import type { Actor, AssistResult, CardData, CardField, CatalogTask, Milestone, MilestoneCode, Proposal, ProposalInput, Rating, ScoreItem, Task, TaskCreateInput, Team, TeamInput } from '../types';
import { emptyCard, FIELD_LABELS, MILESTONES } from '../ui/fields';
import { ApiError } from './errors';
const clone=<T,>(value:T):T=>structuredClone(value);
const now=()=>new Date().toISOString();
const unique=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;
const fields=Object.keys(emptyCard()) as CardField[];
const categories:{key:string;label:string;weights:Partial<Record<CardField,number>>}[]=[{key:'context_need',label:'Контекст и потребность',weights:{context:10,need:10}},{key:'data',label:'Данные и материалы',weights:{data:20}},{key:'expected_result',label:'Ожидаемый результат',weights:{expected_result:15}},{key:'success_criteria',label:'Критерии успеха',weights:{success_criteria:15}},{key:'constraints',label:'Ограничения',weights:{constraints:10}},{key:'users',label:'Пользователи',weights:{users:10}},{key:'contact',label:'Связь с бизнесом',weights:{contact:5,interaction_format:5}}];
export function mockRating(card:CardData,confirmed:CardField[]):Rating {
 let preview=0;const breakdown:ScoreItem[]=categories.map(category=>{let points=0,max=0;const missing:CardField[]=[],unconfirmed:CardField[]=[];for(const [field,weight] of Object.entries(category.weights) as [CardField,number][]){max+=weight;if(card[field].trim()){preview+=weight;if(confirmed.includes(field))points+=weight;else unconfirmed.push(field)}else missing.push(field)}return {key:category.key,label:category.label,points,max_points:max,missing_fields:missing,unconfirmed_fields:unconfirmed,suggestion:missing.length?`Добавьте: ${missing.map(f=>FIELD_LABELS[f].toLowerCase()).join(', ')}.`:unconfirmed.length?'Проверьте и подтвердите заполненные поля.':'Категория заполнена и подтверждена.'}});
 const score=breakdown.reduce((sum,item)=>sum+item.points,0);return {score,preview_score:preview,readiness:score<40?'draft':score<70?'working':score<90?'ready':'priority',breakdown,missing_fields:fields.filter(f=>!card[f].trim()),unconfirmed_fields:fields.filter(f=>!!card[f].trim()&&!confirmed.includes(f))};
}
interface MockStore { actors:Actor[];tasks:Task[];catalog:CatalogTask[];teams:Team[];proposals:Proposal[];milestones:Milestone[] }
function seed():MockStore {
 const actors:Actor[]=[{id:'business-1',name:'Демо-бизнес',role:'business'},...['Импульс','Точка роста','Дельта','Спектр','Орбита'].map((name,i)=>({id:`student-${i+1}`,name,role:'student' as const}))];
 const teams:Team[]=actors.slice(1).map((actor,i)=>({id:`team-${i+1}`,owner_id:actor.id,name:actor.name,interests:[['retail','education','logistics','agriculture','services'][i]],skills:[['Python','React','Аналитика','UX/UI','NLP'][i]],technologies:['Python','React'],points:0}));
 const tasks:Task[]=[],catalog:CatalogTask[]=[];const examples=[['Прогноз спроса для сети кофеен','retail'],['Навигатор стажировок для студентов','education'],['Удобные маршруты для курьеров','logistics'],['Обзор состояния теплицы','agriculture'],['Классификация обращений клиентов','services']];
 const order:CardField[]=['context','need','data','expected_result','success_criteria','constraints','users','contact','interaction_format'];
 examples.forEach(([title,topic],i)=>{const complete:CardData={title,topic,context:`Бизнес хочет улучшить процесс: ${title.toLowerCase()}. Сейчас сотрудники выполняют работу вручную.`,need:'Сократить время ручной работы и уменьшить количество ошибок.',users:'Сотрудники и руководитель направления',data:'CSV за последние 6 месяцев; синтетические примеры предоставим команде.',constraints:'Срок 2 недели. Python, React. Только тестовые данные.',expected_result:'Работающий прототип и короткая инструкция.',success_criteria:'Не менее 16 верных результатов на 20 согласованных тестовых примерах.',contact:'business@example.com',interaction_format:'Созвон раз в неделю и обратная связь в течение двух дней.'};const card=emptyCard(topic);card.title=title;order.slice(0,[2,4,6,7,9][i]).forEach(f=>card[f]=complete[f]);const confirmed=fields.filter(f=>!!card[f]);const task:Task={id:`demo-task-${i+1}`,owner_id:'business-1',raw_description:complete.context,card,revision:1,confirmed_revision:1,published_revision:1,confirmed_fields:confirmed,status:'published',rating:mockRating(card,confirmed),created_at:now()};tasks.push(task);catalog.push({id:task.id,card:clone(card),revision:1,rating:clone(task.rating),published_at:now()});const draftCard=emptyCard(topic);draftCard.title=title;tasks.push({...clone(task),id:`demo-draft-${i+1}`,card:draftCard,confirmed_fields:[],confirmed_revision:null,published_revision:null,status:'draft',rating:mockRating(draftCard,[])})});
 const proposals:Proposal[]=teams.map((team,i)=>({id:`demo-proposal-${i+1}`,task_id:`demo-task-${i+1}`,team_id:team.id,idea:'Соберём прототип и проверим решение на предоставленных тестовых данных.',plan:'Уточнение задачи → изучение данных → прототип → демонстрация.',timeline:'2 недели',prototype_url:'https://example.com/prototype',status:'pending',decision_note:'',created_at:now(),decided_at:null}));return {actors,tasks,catalog,teams,proposals,milestones:[]};
}
let store=seed();
export function resetMocks(){store=seed()}
function fail(message:string,code:string,status=409):never{throw new ApiError(message,code,status)}
function requireActor(actorId:string|undefined,role?:Actor['role']){const actor=store.actors.find(a=>a.id===actorId);if(!actor)fail('Выберите демо-пользователя.','ACTOR_REQUIRED',401);if(role&&actor.role!==role)fail('Это действие недоступно для выбранной роли.',role==='business'?'BUSINESS_REQUIRED':'STUDENT_REQUIRED',403);return actor}
function ownTask(actorId:string|undefined,id:string){const actor=requireActor(actorId,'business');const task=store.tasks.find(t=>t.id===id&&t.owner_id===actor.id);if(!task)fail('Задача не найдена.','TASK_NOT_FOUND',404);return task}
function teamFor(actorId:string|undefined){const actor=requireActor(actorId,'student');const team=store.teams.find(t=>t.owner_id===actor.id);if(!team)fail('Сначала создайте профиль команды.','TEAM_REQUIRED');return team}
function revision(task:Task,input:{expected_revision?:number}){if(input.expected_revision!==task.revision)fail('Карточка изменилась. Загрузите актуальную версию.','STALE_REVISION')}
function nonempty(text:unknown,max=8000){if(typeof text!=='string'||!text.trim()||text.length>max)fail('Заполните обязательные поля и проверьте длину текста.','VALIDATION_ERROR',422)}
function route(path:string,actorId:string|undefined,method:string,body:unknown):unknown {
 const url=new URL(path,'http://mock');const parts=url.pathname.split('/').filter(Boolean).map(decodeURIComponent);const input=(body??{}) as Record<string,unknown>;
 if(path==='/demo/actors')return store.actors;
 if(parts[0]==='catalog'){
  if(parts[1]){const item=store.catalog.find(t=>t.id===parts[1]);return item||fail('Опубликованная задача не найдена.','TASK_NOT_FOUND',404)}
  const topic=url.searchParams.get('topic'),readiness=url.searchParams.get('readiness'),limit=Number(url.searchParams.get('limit')||20),offset=Number(url.searchParams.get('offset')||0);const items=store.catalog.filter(t=>(!topic||t.card.topic===topic)&&(!readiness||t.rating.readiness===readiness)).sort((a,b)=>b.rating.score-a.rating.score||b.published_at.localeCompare(a.published_at));return {items:items.slice(offset,offset+limit),total:items.length,limit,offset};
 }
 if(parts[0]==='teams'){
  if(!parts[1])return store.teams;
  const actor=requireActor(actorId,'student');if(method==='PUT'){const payload=body as TeamInput;nonempty(payload.name,200);for(const list of [payload.interests,payload.skills,payload.technologies]){if(list.length>30)fail('Максимум 30 тегов.','VALIDATION_ERROR',422);list.forEach(t=>nonempty(t,100))}const current=store.teams.find(t=>t.owner_id===actor.id);if(current){Object.assign(current,clone(payload));return current}const team:Team={...clone(payload),id:unique('team'),owner_id:actor.id,points:0};store.teams.push(team);return team}return teamFor(actorId);
 }
 if(parts[0]==='tasks'){
  if(parts.length===1&&method==='POST'){requireActor(actorId,'business');const payload=body as TaskCreateInput;nonempty(payload.raw_description);nonempty(payload.topic,100);const card=emptyCard(payload.topic);card.title=payload.title?.trim()||'';const task:Task={id:unique('task'),owner_id:actorId!,raw_description:payload.raw_description.trim(),card,revision:1,confirmed_revision:null,published_revision:null,confirmed_fields:[],status:'draft',rating:mockRating(card,[]),created_at:now()};store.tasks.unshift(task);return task}
  if(parts[1]==='mine'){requireActor(actorId,'business');return store.tasks.filter(t=>t.owner_id===actorId)}
  if(parts[2]==='proposals'&&method==='POST'){const team=teamFor(actorId);if(!store.catalog.some(t=>t.id===parts[1]))fail('Опубликованная задача не найдена.','TASK_NOT_FOUND',404);const payload=body as ProposalInput;nonempty(payload.idea);nonempty(payload.plan);nonempty(payload.timeline,500);if(payload.prototype_url){try{const link=new URL(payload.prototype_url);if(!['http:','https:'].includes(link.protocol))throw new Error()}catch{fail('Укажите корректную ссылку http:// или https://.','VALIDATION_ERROR',422)}}if(store.proposals.some(p=>p.task_id===parts[1]&&p.team_id===team.id))fail('Ваша команда уже отправила отклик.','CONFLICT');const proposal:Proposal={...clone(payload),id:unique('proposal'),task_id:parts[1],team_id:team.id,status:'pending',decision_note:'',created_at:now(),decided_at:null};store.proposals.push(proposal);return proposal}
  const task=ownTask(actorId,parts[1]);if(parts.length===2)return task;
  if(parts[2]==='proposals')return store.proposals.filter(p=>p.task_id===task.id);
  if(parts[2]==='assist'){const answers=(input.answers||{}) as Partial<Record<CardField,string>>;const card=clone(task.card);if(!card.context)card.context=task.raw_description;Object.entries(answers).forEach(([field,value])=>{if(fields.includes(field as CardField)&&value?.trim())card[field as CardField]=value.trim()});const missing=fields.filter(f=>!card[f].trim());const candidates=[...new Set([...missing,...fields.filter(f=>f!=='topic')])].slice(0,3);const prompts:Partial<Record<CardField,string>>={title:'Как кратко назвать вашу задачу?',data:'Какие данные и материалы вы готовы предоставить?',need:'Какую проблему нужно решить?',success_criteria:'Как вы поймёте, что решение работает?',expected_result:'Какой результат вы хотите получить от команды?'};return {provider:'stub',fallback_reason:null,based_on_revision:task.revision,suggested_card:card,missing_fields:missing,questions:candidates.map(field=>({field,question:prompts[field]||`Уточните поле «${FIELD_LABELS[field]}»: что важно знать команде?`}))} satisfies AssistResult}
  revision(task,input as {expected_revision:number});
  if(parts[2]==='card'){const payload=input.card as CardData;const card=Object.fromEntries(fields.map(f=>[f,typeof payload?.[f]==='string'?payload[f].trim():''])) as CardData;for(const f of fields)if(card[f].length>(f==='title'?200:f==='topic'?100:8000))fail('Превышена длина поля.','VALIDATION_ERROR',422);const changed=fields.some(f=>card[f]!==task.card[f]);if(changed){task.confirmed_fields=task.confirmed_fields.filter(f=>card[f]===task.card[f]&&!!card[f]);task.card=card;task.revision++;task.confirmed_revision=null}task.rating=mockRating(task.card,task.confirmed_fields);return task}
  if(parts[2]==='confirm'){task.confirmed_fields=fields.filter(f=>!!task.card[f].trim());task.confirmed_revision=task.revision;task.rating=mockRating(task.card,task.confirmed_fields);return task}
  if(parts[2]==='publish'){if(task.confirmed_revision!==task.revision)fail('Сначала подтвердите текущую редакцию.','CONFIRMATION_REQUIRED');if(!task.card.title||!task.card.topic)fail('Укажите название задачи и тему.','CARD_LABELS_REQUIRED',422);task.status='published';task.published_revision=task.revision;const snapshot:CatalogTask={id:task.id,card:clone(task.card),rating:clone(task.rating),revision:task.revision,published_at:now()};store.catalog=store.catalog.filter(t=>t.id!==task.id);store.catalog.push(snapshot);return task}
 }
 if(parts[0]==='proposals'){
  if(parts[1]==='mine'){const team=teamFor(actorId);return store.proposals.filter(p=>p.team_id===team.id)}
  const proposal=store.proposals.find(p=>p.id===parts[1]);if(!proposal)fail('Отклик не найден.','PROPOSAL_NOT_FOUND',404);ownTask(actorId,proposal.task_id);
  if(parts[2]==='decision'){const decision=input.decision as 'accepted'|'rejected';if(!['accepted','rejected'].includes(decision))fail('Выберите решение.','VALIDATION_ERROR',422);if(proposal.status!=='pending'&&proposal.status!==decision)fail('Решение уже принято.','DECISION_FINAL');proposal.status=decision;proposal.decision_note=String(input.note||'');proposal.decided_at=now();return proposal}
  if(parts[2]==='milestones'){if(method==='GET')return store.milestones.filter(m=>m.proposal_id===proposal.id);if(proposal.status!=='accepted')fail('Предложение ещё не принято.','TEAM_NOT_SELECTED');const code=input.code as MilestoneCode;const evidence=String(input.evidence||'').trim();nonempty(evidence);if(!MILESTONES[code])fail('Неизвестный этап.','VALIDATION_ERROR',422);const existing=store.milestones.find(m=>m.proposal_id===proposal.id&&m.code===code);if(existing){if(existing.evidence===evidence)return existing;fail('Этот этап уже подтверждён с другим описанием.','MILESTONE_EXISTS')}const milestone:Milestone={id:unique('milestone'),proposal_id:proposal.id,code,evidence,points:MILESTONES[code].points,confirmed_by:actorId!,confirmed_at:now()};store.milestones.push(milestone);const team=store.teams.find(t=>t.id===proposal.team_id)!;team.points+=milestone.points;return milestone}
 }
 return fail('Этот маршрут не поддерживается.','NOT_FOUND',404);
}
export async function mockRequest<T>(path:string,actorId?:string,method='GET',body?:unknown):Promise<T>{await new Promise(resolve=>setTimeout(resolve,180));return clone(route(path,actorId,method,body)) as T}
