import type { CardData, CardField, FieldKey, MilestoneCode } from '../types';
export const FIELD_LABELS: Record<CardField,string> = {title:'Название',topic:'Тема',context:'Контекст',need:'Потребность',users:'Пользователи',data:'Данные и материалы',constraints:'Ограничения',expected_result:'Ожидаемый результат',success_criteria:'Критерии успеха',contact:'Контакт',interaction_format:'Формат взаимодействия'};
export const FIELD_HINTS:Record<FieldKey,string>={title:'Коротко: что нужно сделать?',context:'Что происходит сейчас и почему возникла задача?',need:'Какую проблему вы хотите решить?',users:'Кто будет пользоваться результатом?',data:'Какие данные, файлы и материалы вы предоставите?',constraints:'Сроки, технологии, ограничения и условия работы',expected_result:'Что команда должна передать: прототип, отчёт, сервис?',success_criteria:'Как измерить, что задача решена успешно?',contact:'Контакт ответственного: почта или другой способ связи',interaction_format:'Как часто общаться и получать обратную связь?'};
export const FIELD_GROUPS: {title:string; fields:FieldKey[]}[]=[{title:'Основное',fields:['title','context','need']},{title:'Для кого и с чем',fields:['users','data']},{title:'Результат',fields:['expected_result','success_criteria']},{title:'Рамки',fields:['constraints']},{title:'Связь',fields:['contact','interaction_format']}];
export const TOPICS=[{value:'retail',label:'Ритейл'},{value:'education',label:'Образование'},{value:'logistics',label:'Логистика'},{value:'agriculture',label:'Агротехнологии'},{value:'services',label:'Сервисы'},{value:'healthcare',label:'Здоровье'},{value:'finance',label:'Финансы'},{value:'it',label:'IT и сервисы'},{value:'other',label:'Другое'}];
export const topicLabel=(topic:string)=>TOPICS.find(t=>t.value===topic)?.label||topic||'Без темы';
export const emptyCard=(topic='retail'):CardData=>({title:'',topic,context:'',need:'',users:'',data:'',constraints:'',expected_result:'',success_criteria:'',contact:'',interaction_format:''});
export const MILESTONES:Record<MilestoneCode,{label:string;points:number;description:string}>={prototype:{label:'Прототип',points:20,description:'Первое работающее решение'},pilot:{label:'Пилот',points:30,description:'Проверка на реальной задаче'},delivery:{label:'Передача результата',points:50,description:'Завершённый результат и инструкция'}};
export function formatDate(date:string){return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'long',year:'numeric'}).format(new Date(date));}
export function teamLevel(points:number){const tiers=[{name:'Исследователи',min:0,next:40},{name:'Практики',min:40,next:100},{name:'Создатели',min:100,next:200},{name:'Эксперты',min:200,next:400},{name:'Мастера',min:400,next:null}];const index=tiers.findLastIndex(t=>points>=t.min);const level=tiers[index];return {...level,index:index+1,progress:level.next?Math.min(100,(points-level.min)/(level.next-level.min)*100):100};}
export function matchTask(card:CardData,team:{interests:string[];skills:string[];technologies:string[]}){const haystack=Object.values(card).join(' ').toLocaleLowerCase('ru');const candidates=[...team.interests,...team.skills,...team.technologies];return [...new Set(candidates)].filter(tag=>haystack.includes(tag.toLocaleLowerCase('ru'))||topicLabel(card.topic).toLocaleLowerCase('ru').includes(tag.toLocaleLowerCase('ru')));}
